# Generated by Django 4.0.4 on 2022-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_createtask_createteam_createuser_taskmodel_teammodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('taskdesc', models.TextField()),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
