# Generated by Django 4.0.4 on 2022-05-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_taskmodels_delete_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodels',
            name='completed',
            field=models.DateTimeField(),
        ),
    ]
