# Generated by Django 4.0.4 on 2022-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_taskmodels_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodels',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
